# Generated by Django 3.2.7 on 2021-09-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210904_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalog',
            field=models.FileField(default=None, upload_to='media/', verbose_name='کاتالوگ'),
        ),
    ]
