# Generated by Django 3.2.7 on 2021-09-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('N', 'Not_Exist'), ('A', 'Active'), ('W', 'Will_not_be_produced'), ('O', 'Ordered')], default='N', max_length=1, verbose_name='وضعیت موجودی'),
        ),
    ]
