# Generated by Django 3.2.7 on 2021-09-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='media',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='is_acrive',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('numeric_value', models.IntegerField(blank=True, null=True)),
                ('string_value', models.CharField(blank=True, max_length=200, null=True)),
                ('att_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='filed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attribute', verbose_name='فیلد اضافی'),
        ),
    ]
